### ISSUE TITLE
crash when opening a markdown file

### ISSUE THREAD

**Issue by bitbonk** [fluentCODE/ScrawlIssues#106]
This the markdown file:

https://gist.github.com/bitbonk/713b9a8de0d19c0dd96c

This is the excpetion:

System.AccessViolationException was unhandled
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=OnigRegex
  StackTrace:
       at OnigRegex.OnigInterop.onigwrap_search(IntPtr regex, String text, Int32 offset, Int32 length)
       at OnigRegex.ORegex.Search(String text, Int32 offset)
       at OnigRegex.ORegex.SafeSearch(String text, Int32 offset, List`1 resultList)
       at Scrawl.Editor.TextMate.TMLexer.FindLineMatches(LexerState state)
       at Scrawl.Editor.TextMate.TMLexer.ProcessLines(LexerState state)
       at Scrawl.Editor.TextMate.TMLexer.ProcessLines(LexerState state)
       at Scrawl.Editor.TextMate.TMLexer.ProcessLines(LexerState state)
       at Scrawl.Editor.TextMate.TMLexer.ProcessLines(LexerState state)
       at Scrawl.Editor.TextMate.TMLexer.UpdateRanges(Line line, Range defaultRange, Int32 cap)
       at Scrawl.Editor.TextMate.LexerEngine.ProcessBackgroundQueueUntilEmpty()
       at Scrawl.Editor.TextMate.LexerEngine.<Enqueue>b__3_0()
       at System.Threading.Tasks.Task.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()
       at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
       at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
       at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
  InnerException:

**Comment by pauljz** [comment]
This is fixed in the dev branch now (https://twitter.com/scrawlcommits/status/582671348314566656), but I can't easily cherry pick this one.

 Leaving it open until we merge our dev branch and push a new CI build.
