### ISSUE TITLE
VB file causes crash

### ISSUE THREAD

**Issue by xavierzwirtz** [fluentCODE/ScrawlIssues#115]
Opening any VB file causes scrawl to crash with this exception:

```
Application: Scrawl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at Scrawl.CodeEngine.Roslyn.RoslynCodeEngine.OpenFile(Scrawl.Common.CodeEngine.Request, System.String)
   at Scrawl.Editor.Models.Document.FindOrCreate(System.String)
   at Scrawl.App.Windows.BaseForm.OpenFile(System.Collections.Generic.IEnumerable`1<System.String>, Boolean)
   at Scrawl.Common.Forms.BaseForm.OpenFileDialog()
   at Scrawl.Common.Forms.BaseForm.BaseForm_KeyDown(System.Object, Eto.Forms.KeyEventArgs)
   at Eto.PropertyStore.TriggerEvent[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object, System.Object, System.__Canon)
   at Eto.Forms.Control.OnKeyDown(Eto.Forms.KeyEventArgs)
   at Eto.Forms.Control+Callback+<>c__DisplayClass0.<OnKeyDown>b__1()
   at Eto.Platform.Invoke(System.Action)
   at Eto.Forms.Control+Callback.OnKeyDown(Eto.Forms.Control, Eto.Forms.KeyEventArgs)
   at Eto.WinForms.Forms.ApplicationHandler+<>c__DisplayClass0.<SetOptions>b__21(Eto.Forms.Control, ICallback, Eto.Forms.KeyEventArgs)
   at Eto.WinForms.BubbleEventFilter.KeyEvent(Eto.WinForms.BubbleEventArgs, System.Action`3<Eto.Forms.Control,ICallback,Eto.Forms.KeyEventArgs>, Eto.Forms.KeyEventType)
   at Eto.WinForms.BubbleEventFilter+<>c__DisplayClass0.<AddBubbleKeyEvent>b__1(Eto.WinForms.BubbleEventArgs)
   at Eto.WinForms.BubbleEventFilter.PreFilterMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Application+ThreadContext.ProcessFilters(MSG ByRef, Boolean ByRef)
   at System.Windows.Forms.Application+ThreadContext.PreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at Eto.WinForms.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Eto.Forms.Form)
   at Scrawl.App.Windows.Program.Main(System.String[])

```

**Comment by JonBons** [comment]
I'm seeing the same. 

I created an empty file named 'EmptyFile.vb' and attempted to open the file via the 'Open' menu option and nothing happened. I then opened the directory the file was located in with the File Explorer and I got the same crash as above.

```
Application: Scrawl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at Scrawl.CodeEngine.Roslyn.RoslynCodeEngine.OpenFile(Scrawl.Common.CodeEngine.Request, System.String)
   at Scrawl.Editor.Models.Document.FindOrCreate(System.String)
   at Scrawl.App.Windows.BaseForm.OpenFile(System.Collections.Generic.IEnumerable`1<System.String>, Boolean)
   at Scrawl.Common.Controls.FolderExplorer.FolderExplorer_FileOpened(System.Object, Scrawl.Common.Controls.FileSystemTreeViewItemEventArgs)
   at Scrawl.Common.Controls.FileSystemTreeView.FileSystemTreeView_ItemDoubleClicked(System.Object, Scrawl.Common.Controls.TreeViewItemEventArgs`1<Scrawl.Common.Controls.FileSystemTreeViewItem>)
   at Scrawl.Common.Controls.TreeView`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TreeView_MouseDown(System.Object, Eto.Forms.MouseEventArgs)
   at Eto.PropertyStore.TriggerEvent[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object, System.Object, System.__Canon)
   at Eto.Forms.Control.OnMouseDown(Eto.Forms.MouseEventArgs)
   at Eto.Forms.Control+Callback+<>c__DisplayClass4.<OnMouseDown>b__5()
   at Eto.Platform.Invoke(System.Action)
   at Eto.Forms.Control+Callback.OnMouseDown(Eto.Forms.Control, Eto.Forms.MouseEventArgs)
   at Eto.WinForms.Forms.ApplicationHandler+<>c__DisplayClass0.<SetOptions>b__7(Eto.Forms.Control, ICallback, Eto.Forms.MouseEventArgs)
   at Eto.WinForms.BubbleEventFilter.MouseEvent(Eto.WinForms.BubbleEventArgs, System.Action`3<Eto.Forms.Control,ICallback,Eto.Forms.MouseEventArgs>, System.Nullable`1<Boolean>, System.Func`2<Eto.Forms.MouseButtons,Eto.Forms.MouseButtons>)
   at Eto.WinForms.BubbleEventFilter+<>c__DisplayClass6.<AddBubbleMouseEvents>b__7(Eto.WinForms.BubbleEventArgs)
   at Eto.WinForms.BubbleEventFilter.PreFilterMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Application+ThreadContext.ProcessFilters(MSG ByRef, Boolean ByRef)
   at System.Windows.Forms.Application+ThreadContext.PreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at Eto.WinForms.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Eto.Forms.Form)
   at Scrawl.App.Windows.Program.Main(System.String[])
```

**Comment by stirno** [comment]
Looks like the code engine in dev has a serious aversion to poor VB. Will get it taken care of soon :)

**Comment by StachuDotNet** [comment]
Discouraging VB sounds like a feature, not a bug ;)

**Comment by xavierzwirtz** [comment]
Agreed, I wont be able to get my org to move over to Scrawl without VB support though.

**Comment by rondefreitas** [comment]
Also, going forward Microsoft doesn't seem too keen on continuing to support Visual Basic.  It's been left behind for ASP.NET 5

**Comment by pauljz** [comment]
Doesn't crash on the dev branch anymore!

![everyone-loves-vb](https://cloud.githubusercontent.com/assets/666213/6934743/3c2da948-d7ff-11e4-9333-fecbc7fe2c41.png)
