### ISSUE TITLE
Crash on app start with new update

### ISSUE THREAD

**Issue by xavierzwirtz** [fluentCODE/ScrawlIssues#125]
Crashes as soon as launch scrawl. Error from event viewer:

```
Application: Scrawl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException
Stack:
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CommonInit()
   at System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.String, System.String, System.String, System.IO.SearchOption, System.IO.SearchResultHandler`1<System.__Canon>, Boolean)
   at System.IO.Directory.EnumerateFiles(System.String, System.String, System.IO.SearchOption)
   at Scrawl.Sdk.PluginService..ctor()
   at Scrawl.Sdk.Workspace.WorkspaceService..ctor()
   at Scrawl.Sdk.Workspace.WorkspaceService.get_Current()
   at Scrawl.Common.Controls.WorkspaceTreeView..ctor()
   at Scrawl.Common.Controls.WorkspaceExplorer..ctor()
   at Scrawl.Common.Controls.WorkspaceExplorer.get_Current()
   at Scrawl.Common.Controls.WorkspaceExplorer.Create()
   at Scrawl.App.Windows.Program.Main(System.String[])
```

**Comment by stirno** [comment]
Got a fix going in for this now. .Looks like we overlooked actually creating the plugin dir from code. oops.

To fix it locally so you can update, create the following directory:

%AppData%\Scrawl\plugins

**Comment by xavierzwirtz** [comment]
:laughing: 
That fixed it.

**Comment by stirno** [comment]
Fixed in 304 which is the updated installer as well. Closing :)
