### ISSUE TITLE
Opening folders in a project causes crash

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#126]
1. Open this solution (as emailed)
2. Click into workspace explorer
3. try to open one of the folders in the project
   exception is: Application: Scrawl.exe
   Framework Version: v4.0.30319
   Description: The process was terminated due to an unhandled exception.
   Exception Info: System.NullReferenceException
   Stack:
   at Scrawl.Common.Controls.WorkspaceTreeView.LoadChildren(Scrawl.Common.Controls.WorkspaceTreeViewItem)
   at Scrawl.Common.Controls.WorkspaceTreeView.WorkspaceTreeView_ItemClicked(System.Object, Scrawl.Common.Controls.TreeViewItemEventArgs`1<Scrawl.Common.Controls.WorkspaceTreeViewItem>)
   at Scrawl.Common.Controls.TreeView`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TreeView_MouseDown(System.Object, Eto.Forms.MouseEventArgs)
   at Eto.PropertyStore.TriggerEvent[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object, System.Object, System.__Canon)
   at Eto.Forms.Control.OnMouseDown(Eto.Forms.MouseEventArgs)
   at Eto.Forms.Control+Callback+<>c__DisplayClass4.<OnMouseDown>b__5()
   at Eto.Platform.Invoke(System.Action)
   at Eto.Forms.Control+Callback.OnMouseDown(Eto.Forms.Control, Eto.Forms.MouseEventArgs)
   at Eto.WinForms.Forms.ApplicationHandler+<>c.<SetOptions>b__17_2(Eto.Forms.Control, ICallback, Eto.Forms.MouseEventArgs)
   at Eto.WinForms.BubbleEventFilter.MouseEvent(Eto.WinForms.BubbleEventArgs, System.Action`3<Eto.Forms.Control,ICallback,Eto.Forms.MouseEventArgs>, System.Nullable`1<Boolean>, System.Func`2<Eto.Forms.MouseButtons,Eto.Forms.MouseButtons>)
   at Eto.WinForms.BubbleEventFilter+<>c__DisplayClass7_0.<AddBubbleMouseEvents>b__0(Eto.WinForms.BubbleEventArgs)
   at Eto.WinForms.BubbleEventFilter.PreFilterMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Application+ThreadContext.ProcessFilters(MSG ByRef, Boolean ByRef)
   at System.Windows.Forms.Application+ThreadContext.PreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at Eto.WinForms.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Eto.Forms.Form)
   at Scrawl.App.Windows.Program.Main(System.String[])

**Comment by stirno** [comment]
gif pls? very likely something specific about the folder being opened that we might be able to see from it.

**Comment by stirno** [comment]
nevemrind that question. fixed in latest.
