### ISSUE TITLE
NullReference when clicking *.files

### ISSUE THREAD

**Issue by yannisgu** [fluentCODE/ScrawlIssues#39]
Steps to reproduce:
1. Open a Visual Studio solution
2. Add a new file with File => New File
3. Click on `*.files` in the workspace explorer

Scawl crashes with

```
Exception Info: System.NullReferenceException
Stack:
   at Scrawl.Common.Controls.WorkspaceTreeView.DirectoryItems(Scrawl.Common.Controls.WorkspaceTreeViewItem, System.Collections.Generic.IEnumerable`1<Scrawl.Common.Workspace.File>)
   at Scrawl.Common.Controls.WorkspaceTreeView.LoadChildren(Scrawl.Common.Controls.WorkspaceTreeViewItem)
   at Scrawl.Common.Controls.WorkspaceTreeView.WorkspaceTreeView_ItemClicked(System.Object, Scrawl.Common.Controls.TreeViewItemEventArgs`1<Scrawl.Common.Controls.WorkspaceTreeViewItem>)
   at Scrawl.Common.Controls.TreeView`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TreeView_MouseDown(System.Object, Eto.Forms.MouseEventArgs)
   at Eto.PropertyStore.TriggerEvent[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object, System.Object, System.__Canon)
   at Eto.Forms.Control.OnMouseDown(Eto.Forms.MouseEventArgs)
   at Eto.Forms.Control+Callback+<>c__DisplayClass4.<OnMouseDown>b__5()
   at Eto.Platform.Invoke(System.Action)
   at Eto.Forms.Control+Callback.OnMouseDown(Eto.Forms.Control, Eto.Forms.MouseEventArgs)
   at Eto.WinForms.Forms.ApplicationHandler+<>c__DisplayClass0.<SetOptions>b__5(Eto.Forms.Control, ICallback, Eto.Forms.MouseEventArgs)
   at Eto.WinForms.BubbleEventFilter.MouseEvent(Eto.WinForms.BubbleEventArgs, System.Action`3<Eto.Forms.Control,ICallback,Eto.Forms.MouseEventArgs>, System.Nullable`1<Boolean>, System.Func`2<Eto.Forms.MouseButtons,Eto.Forms.MouseButtons>)
   at Eto.WinForms.BubbleEventFilter+<>c__DisplayClass6.<AddBubbleMouseEvents>b__7(Eto.WinForms.BubbleEventArgs)
   at Eto.WinForms.BubbleEventFilter.PreFilterMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Application+ThreadContext.ProcessFilters(MSG ByRef, Boolean ByRef)
   at System.Windows.Forms.Application+ThreadContext.PreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at Eto.WinForms.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Eto.Forms.Form)
   at Scrawl.App.Windows.Program.Main(System.String[])
```

**Comment by stirno** [comment]
Fixed in #184. https://twitter.com/scrawlcommits/status/575073099500118017
