### ISSUE TITLE
When pressing "Delete" when cursor is at the end of the file, then.. you bet it

### ISSUE THREAD

**Issue by yannisgu** [fluentCODE/ScrawlIssues#43]
When pressing "Delete" when the cursor is at the end of a file, Scawl falls back to Visual Studio mode with the following Exception:

```
Application: Scrawl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
Stack:
   at System.Char.IsHighSurrogate(System.String, Int32)
   at Scrawl.Editor.Models.Cursor+<>c__DisplayClass3_0.<Delete>b__0(Scrawl.Editor.Models.Document)
   at Scrawl.Editor.UndoRedoManager.Do(Scrawl.Editor.UndoRedoCommand, Boolean)
   at Scrawl.Editor.Models.Cursor.Delete(Boolean, Boolean)
   at Scrawl.Editor.Controls.EditorControl.Editor_KeyDown(System.Object, Eto.Forms.KeyEventArgs)
   at Eto.PropertyStore.TriggerEvent[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object, System.Object, System.__Canon)
   at Eto.Forms.Control.OnKeyDown(Eto.Forms.KeyEventArgs)
   at Eto.Forms.Control+Callback+<>c__DisplayClass0.<OnKeyDown>b__1()
   at Eto.Platform.Invoke(System.Action)
   at Eto.Forms.Control+Callback.OnKeyDown(Eto.Forms.Control, Eto.Forms.KeyEventArgs)
   at Eto.WinForms.Forms.ApplicationHandler+<>c__DisplayClass0.<SetOptions>b__21(Eto.Forms.Control, ICallback, Eto.Forms.KeyEventArgs)
   at Eto.WinForms.BubbleEventFilter.KeyEvent(Eto.WinForms.BubbleEventArgs, System.Action`3<Eto.Forms.Control,ICallback,Eto.Forms.KeyEventArgs>, Eto.Forms.KeyEventType)
   at Eto.WinForms.BubbleEventFilter+<>c__DisplayClass0.<AddBubbleKeyEvent>b__1(Eto.WinForms.BubbleEventArgs)
   at Eto.WinForms.BubbleEventFilter.PreFilterMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Application+ThreadContext.ProcessFilters(MSG ByRef, Boolean ByRef)
   at System.Windows.Forms.Application+ThreadContext.PreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at Eto.WinForms.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Eto.Forms.Form)
   at Scrawl.App.Windows.Program.Main(System.String[])

```

**Comment by pauljz** [comment]
Fixed by https://twitter.com/scrawlcommits/status/575025798446456832
