### ISSUE TITLE
Scrawl crashes on pressing enter sometimes

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#63]
![scrawlcrashing](https://cloud.githubusercontent.com/assets/396538/6583511/8ab79cd0-c75c-11e4-98dc-673471dd4204.gif)

I pressed enter after the second class definition at the end and Scrawl crashed.

```
Error log: Application: Scrawl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
Stack:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
   at System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Item(Int32)
   at Scrawl.Editor.Models.Cursor+<>c__DisplayClass30_0.<Insert>b__0(Scrawl.Editor.Models.Document)
   at Scrawl.Editor.UndoRedoManager.Do(Scrawl.Editor.UndoRedoCommand, Boolean)
   at Scrawl.Editor.Models.Cursor.Insert(System.String, Boolean, Boolean)
   at Scrawl.Editor.Controls.EditorControl.Editor_KeyDown(System.Object, Eto.Forms.KeyEventArgs)
   at Eto.PropertyStore.TriggerEvent[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object, System.Object, System.__Canon)
   at Eto.Forms.Control.OnKeyDown(Eto.Forms.KeyEventArgs)
   at Eto.Forms.Control+Callback+<>c__DisplayClass0.<OnKeyDown>b__1()
   at Eto.Platform.Invoke(System.Action)
   at Eto.Forms.Control+Callback.OnKeyDown(Eto.Forms.Control, Eto.Forms.KeyEventArgs)
   at Eto.WinForms.Forms.ApplicationHandler+<>c__DisplayClass0.<SetOptions>b__21(Eto.Forms.Control, ICallback, Eto.Forms.KeyEventArgs)
   at Eto.WinForms.BubbleEventFilter.KeyEvent(Eto.WinForms.BubbleEventArgs, System.Action`3<Eto.Forms.Control,ICallback,Eto.Forms.KeyEventArgs>, Eto.Forms.KeyEventType)
   at Eto.WinForms.BubbleEventFilter+<>c__DisplayClass0.<AddBubbleKeyEvent>b__1(Eto.WinForms.BubbleEventArgs)
   at Eto.WinForms.BubbleEventFilter.PreFilterMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Application+ThreadContext.ProcessFilters(MSG ByRef, Boolean ByRef)
   at System.Windows.Forms.Application+ThreadContext.PreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at Eto.WinForms.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Eto.Forms.Form)
   at Scrawl.App.Windows.Program.Main(System.String[])
```

**Comment by pauljz** [comment]
The bugs that cause this should be fixed in build 211.
