### ISSUE TITLE
Exception when opening file

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#90]
Scrawl is crashing when I open files right now. Exception is:

```
   at System.Windows.Forms.Control.set_BackColor(System.Drawing.Color)
   at System.Windows.Forms.Form.set_BackColor(System.Drawing.Color)
   at Eto.WinForms.Forms.WindowsControl`3[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].set_BackgroundColor(Eto.Drawing.Color)
   at Scrawl.Editor.Controls.SnippetPrompt..ctor(Scrawl.Editor.Controls.EditorControl)
   at Scrawl.Editor.Controls.EditorControl.Editor_Load(System.Object, System.EventArgs)
   at Eto.PropertyStore.TriggerEvent[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object, System.Object, System.__Canon)
   at Eto.Forms.Control.OnLoad(System.EventArgs)
   at Eto.Forms.Container.OnLoad(System.EventArgs)
   at Eto.Forms.Control.TriggerLoad(System.EventArgs)
   at Eto.Forms.Container.OnLoad(System.EventArgs)
   at Eto.Forms.Control.TriggerLoad(System.EventArgs)
   at Eto.Forms.Container.OnLoad(System.EventArgs)
   at Eto.Forms.Control.TriggerLoad(System.EventArgs)
   at Eto.Forms.Container.OnLoad(System.EventArgs)
   at Eto.Forms.Control.TriggerLoad(System.EventArgs)
   at Eto.Forms.Container.SetParent(Eto.Forms.Control, System.Action, Eto.Forms.Control)
   at Eto.Forms.Panel.set_Content(Eto.Forms.Control)
   at Scrawl.Layout.Tabs.TabControl.Tab_Activated(System.Object, System.EventArgs)
   at Scrawl.Layout.Tabs.TabButton.Activate(Boolean)
   at Scrawl.Layout.Tabs.TabControl.Preview(Eto.Forms.Control)
   at Scrawl.Layout.Tabs.TabContentPresenter.Preview(Eto.Forms.Control)
   at Scrawl.Layout.LayoutItem.Preview(Eto.Forms.Control)
   at Scrawl.Layout.LayoutManager.Preview(Eto.Forms.Control)
   at Scrawl.App.Windows.BaseForm.PreviewFile(System.String)
   at Scrawl.Common.Controls.WorkspaceExplorer.WorkspaceExplorer_FilePreview(System.Object, Scrawl.Common.Controls.WorkspaceTreeViewItemEventArgs)
   at Scrawl.Common.Controls.WorkspaceTreeView.WorkspaceTreeView_ItemClicked(System.Object, Scrawl.Common.Controls.TreeViewItemEventArgs`1<Scrawl.Common.Controls.WorkspaceTreeViewItem>)
   at Scrawl.Common.Controls.TreeView`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].TreeView_MouseDown(System.Object, Eto.Forms.MouseEventArgs)
   at Eto.PropertyStore.TriggerEvent[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object, System.Object, System.__Canon)
   at Eto.Forms.Control.OnMouseDown(Eto.Forms.MouseEventArgs)
   at Eto.Forms.Control+Callback+<>c__DisplayClass4.<OnMouseDown>b__5()
   at Eto.Platform.Invoke(System.Action)
   at Eto.Forms.Control+Callback.OnMouseDown(Eto.Forms.Control, Eto.Forms.MouseEventArgs)
   at Eto.WinForms.Forms.ApplicationHandler+<>c__DisplayClass0.<SetOptions>b__5(Eto.Forms.Control, ICallback, Eto.Forms.MouseEventArgs)
   at Eto.WinForms.BubbleEventFilter.MouseEvent(Eto.WinForms.BubbleEventArgs, System.Action`3<Eto.Forms.Control,ICallback,Eto.Forms.MouseEventArgs>, System.Nullable`1<Boolean>, System.Func`2<Eto.Forms.MouseButtons,Eto.Forms.MouseButtons>)
   at Eto.WinForms.BubbleEventFilter+<>c__DisplayClass6.<AddBubbleMouseEvents>b__7(Eto.WinForms.BubbleEventArgs)
   at Eto.WinForms.BubbleEventFilter.PreFilterMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Application+ThreadContext.ProcessFilters(MSG ByRef, Boolean ByRef)
   at System.Windows.Forms.Application+ThreadContext.PreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at Eto.WinForms.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Eto.Forms.Form)
   at Scrawl.App.Windows.Program.Main(System.String[])
```

**Comment by pauljz** [comment]
@stirno fixed this in build 261 https://twitter.com/scrawlcommits/status/576925851566104577
