### ISSUE TITLE
Scrawl crashes in sequence of events after method argument intellisense used

### ISSUE THREAD

**Issue by dpen2000** [fluentCODE/ScrawlIssues#93]
![scrawlcrash2](https://cloud.githubusercontent.com/assets/396538/6654527/8120ee92-cac2-11e4-9c1b-354bad1fe5a2.gif)

Here I:
1. Pick one method and press tab to get method arguments
2. Clear that method
3. Move down the list of methods
4. Press tab and then space
5. Scrawl crashes
Expect to see new method argument intellisense for newly picked method

Exception is:
Exception Info: System.ArgumentOutOfRangeException
Stack:
   at System.String.Substring(Int32, Int32)
   at Scrawl.Editor.Models.Selection.DeleteSelectionSingleLine(Scrawl.Common.CodeEngine.ChangeRequest, Scrawl.Common.CodeEngine.ChangeRequest)
   at Scrawl.Editor.Models.Selection+<>c__DisplayClass38_0.<Delete>b__0(Scrawl.Editor.Models.Document)
   at Scrawl.Editor.UndoRedoManager.Do(Scrawl.Editor.UndoRedoCommand, Boolean)
   at Scrawl.Editor.Models.Selection.Delete(Boolean)
   at Scrawl.Editor.DocumentManager.ClearAndDeleteSelections()
   at Scrawl.Editor.Controls.EditorControl.Editor_KeyDown(System.Object, Eto.Forms.KeyEventArgs)
   at Eto.PropertyStore.TriggerEvent[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Object, System.Object, System.__Canon)
   at Eto.Forms.Control.OnKeyDown(Eto.Forms.KeyEventArgs)
   at Eto.Forms.Control+Callback+<>c__DisplayClass0.<OnKeyDown>b__1()
   at Eto.Platform.Invoke(System.Action)
   at Eto.Forms.Control+Callback.OnKeyDown(Eto.Forms.Control, Eto.Forms.KeyEventArgs)
   at Eto.WinForms.Forms.ApplicationHandler+<>c__DisplayClass0.<SetOptions>b__23(Eto.Forms.Control, ICallback, Eto.Forms.KeyEventArgs)
   at Eto.WinForms.BubbleEventFilter.KeyCharEvent(Eto.WinForms.BubbleEventArgs, System.Action`3<Eto.Forms.Control,ICallback,Eto.Forms.KeyEventArgs>, Eto.Forms.KeyEventType)
   at Eto.WinForms.BubbleEventFilter+<>c__DisplayClass2.<AddBubbleKeyCharEvent>b__3(Eto.WinForms.BubbleEventArgs)
   at Eto.WinForms.BubbleEventFilter.PreFilterMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Application+ThreadContext.ProcessFilters(MSG ByRef, Boolean ByRef)
   at System.Windows.Forms.Application+ThreadContext.PreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FPreTranslateMessage(MSG ByRef)
   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)
   at System.Windows.Forms.Application.Run(System.Windows.Forms.Form)
   at Eto.WinForms.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Eto.Forms.Form)
   at Scrawl.App.Windows.Program.Main(System.String[])

**Comment by stirno** [comment]
Well.. new code in dev but this still wreaks havoc in whole new ways! :) Will look at it more closely soon.
